//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// このソース コードは xsd によって自動生成されました。Version=4.8.3928.0 です。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="BveEx.Toukaitetudou.Smoke.Config.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="BveEx.Toukaitetudou.Smoke.Config.xsd", IsNullable=false)]
public partial class Config {
    
    private ConfigDrain drainField;
    
    private ConfigChimney chimneyField;
    
    /// <remarks/>
    public ConfigDrain Drain {
        get {
            return this.drainField;
        }
        set {
            this.drainField = value;
        }
    }
    
    /// <remarks/>
    public ConfigChimney Chimney {
        get {
            return this.chimneyField;
        }
        set {
            this.chimneyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="BveEx.Toukaitetudou.Smoke.Config.xsd")]
public partial class ConfigDrain {
    
    private Structure[] structureField;
    
    private double xField;
    
    private bool xFieldSpecified;
    
    private double yField;
    
    private bool yFieldSpecified;
    
    private double zField;
    
    private bool zFieldSpecified;
    
    private System.DateTime generateSpanField;
    
    private bool generateSpanFieldSpecified;
    
    private System.DateTime lifeSpanField;
    
    private bool lifeSpanFieldSpecified;
    
    private System.DateTime continueTimeField;
    
    private bool continueTimeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Structure")]
    public Structure[] Structure {
        get {
            return this.structureField;
        }
        set {
            this.structureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XSpecified {
        get {
            return this.xFieldSpecified;
        }
        set {
            this.xFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool YSpecified {
        get {
            return this.yFieldSpecified;
        }
        set {
            this.yFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ZSpecified {
        get {
            return this.zFieldSpecified;
        }
        set {
            this.zFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime GenerateSpan {
        get {
            return this.generateSpanField;
        }
        set {
            this.generateSpanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GenerateSpanSpecified {
        get {
            return this.generateSpanFieldSpecified;
        }
        set {
            this.generateSpanFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime LifeSpan {
        get {
            return this.lifeSpanField;
        }
        set {
            this.lifeSpanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LifeSpanSpecified {
        get {
            return this.lifeSpanFieldSpecified;
        }
        set {
            this.lifeSpanFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime ContinueTime {
        get {
            return this.continueTimeField;
        }
        set {
            this.continueTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ContinueTimeSpecified {
        get {
            return this.continueTimeFieldSpecified;
        }
        set {
            this.continueTimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="BveEx.Toukaitetudou.Smoke.Config.xsd")]
public partial class Structure {
    
    private string pathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="BveEx.Toukaitetudou.Smoke.Config.xsd")]
public partial class ConfigChimney {
    
    private Structure[] structureField;
    
    private double xField;
    
    private bool xFieldSpecified;
    
    private double yField;
    
    private bool yFieldSpecified;
    
    private double zField;
    
    private bool zFieldSpecified;
    
    private System.DateTime generateSpanField;
    
    private bool generateSpanFieldSpecified;
    
    private System.DateTime lifeSpanField;
    
    private bool lifeSpanFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Structure")]
    public Structure[] Structure {
        get {
            return this.structureField;
        }
        set {
            this.structureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XSpecified {
        get {
            return this.xFieldSpecified;
        }
        set {
            this.xFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool YSpecified {
        get {
            return this.yFieldSpecified;
        }
        set {
            this.yFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Z {
        get {
            return this.zField;
        }
        set {
            this.zField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ZSpecified {
        get {
            return this.zFieldSpecified;
        }
        set {
            this.zFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime GenerateSpan {
        get {
            return this.generateSpanField;
        }
        set {
            this.generateSpanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GenerateSpanSpecified {
        get {
            return this.generateSpanFieldSpecified;
        }
        set {
            this.generateSpanFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime LifeSpan {
        get {
            return this.lifeSpanField;
        }
        set {
            this.lifeSpanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LifeSpanSpecified {
        get {
            return this.lifeSpanFieldSpecified;
        }
        set {
            this.lifeSpanFieldSpecified = value;
        }
    }
}
